tests:
### uDTN default Storage test
  - name: storage-default
    timeout: 1200
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-storage-test
        instrument: [examples/uDTN/storage-test/uDTN-storage-test.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-fno-inline -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30 -DTEST_NO_NETWORK=1"
        graph_options: ""
  - name: storage-default-debug
    timeout: 1200
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-storage-test
        instrument: []
        debug: [examples/uDTN/storage-test/uDTN-storage-test.c,core/net/uDTN/*.c]
        cflags: "-fno-inline -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=0 -DPROFILES_CONF_STACKSIZE=0 -DTEST_NO_NETWORK=1"
        graph_options: ""
  - name: storage-default-uninstr
    timeout: 1200
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-storage-test
        instrument: []
        debug: []
        cflags: "-fno-inline -DCONF_DEST_NODE=$SENDER -DTEST_NO_NETWORK=1"
        graph_options: ""
### uDTN coffee Storage test
  - name: storage-coffee
    timeout: 2400
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-storage-test
        instrument: [examples/uDTN/storage-test/uDTN-storage-test.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DBUNDLE_CONF_STORAGE_INIT=1 -fno-inline -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30 -DBUNDLE_CONF_STORAGE=storage_coffee"
        graph_options: ""
  - name: storage-coffee-uninstr
    timeout: 2400
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-storage-test
        instrument: []
        debug: []
        cflags: "-DBUNDLE_CONF_STORAGE_INIT=1 -fno-inline -DCONF_DEST_NODE=$SENDER -DBUNDLE_CONF_STORAGE=storage_coffee"
        graph_options: ""
### uDTN persistent Storage test
  - name: persistent-storage-coffee
    timeout: 2400
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-persistent-storage-test
        instrument: [examples/uDTN/storage-test/uDTN-persistent-storage-test.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-fno-inline -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30 -DBUNDLE_CONF_STORAGE=storage_coffee"
        graph_options: ""
  - name: persistent-storage-coffee-uninstr
    timeout: 2400
    devices:
      - name: receiver
        programdir: examples/uDTN/storage-test
        program: uDTN-persistent-storage-test
        instrument: []
        debug: []
        cflags: "-fno-inline -DCONF_DEST_NODE=$SENDER -DBUNDLE_CONF_STORAGE=storage_coffee"
        graph_options: ""
